name: CML-Pipeline

on:
  workflow_dispatch:
  push:
    branches:    
      - Feature
  pull_request:
    branches:    
      - main
      - Feature
  
env:
  APPLICATION_NAME: mlapp

jobs:
  training_job:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \ 
          -H "Authorization: token REPO_TOKEN" \
          https://api.github.com/repos/sawansolanki/CML-Demo-ML/actions/runs
          pip install -r requirements.txt
          python training-model.py
          cat metrics.txt >> report.md
          cml publish Precision-Recall-Curve.png --md >> report.md
          cml send-comment report.md
